ignore:
  - main.go
coverage:
  range: "70..90"
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

